image: docker:latest
services:
  - docker:dind

stages:
  - build

variables:
  GIT_STRATEGY: clone

before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}

build_dspln:
  stage: build
  only:
    - branches
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/by-commit/dspln:${CI_COMMIT_SHA} .
    - docker push ${CI_REGISTRY_IMAGE}/by-commit/dspln:${CI_COMMIT_SHA}

release_dspln:
  stage: build
  only:
    - tags
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/by-release/dspln:${CI_COMMIT_TAG} .
    - docker push ${CI_REGISTRY_IMAGE}/by-release/dspln:${CI_COMMIT_TAG}
